### ISSUE TITLE
"createRaribleSdk" function throws TypeError

### ISSUE THREAD

**Issue by zakariamofaddel** [rarible/sdk#126]
Hi guys, my app suddenly broke as the "createRaribleSdk" function from "@rarible/sdk" throws a TypeError.

This is the call stack:

```
error -->  TypeError: EthereumApiClient.Erc20BalanceControllerApi is not a constructor
    at createEthereumApis (apis.js?e061:17:1)
    at createRaribleSdk (index.js?59ca:39:1)
    at createEthereumSdk (index.js?4b29:17:1)
    at createRaribleSdk (index.js?0a32:18:1)
    at eval (index.tsx?07ff:59:44)
```

**Comment by dsuthardeqode** [comment]
Hi @zakariamofaddel, try upgrading the version of the following libraries that you are using:
- `rarible/sdk` : `~0.8.30`
- `rarible/web3-ethereum` : `~0.12.26`

**Comment by zakariamofaddel** [comment]
> Hi @zakariamofaddel, try upgrading the version of the following libraries that you are using:
> 
> * `rarible/sdk` : `~0.8.30`
> * `rarible/web3-ethereum` : `~0.12.26`



Solved everything by upgrading to:
```
 "@rarible/sdk": "^0.8.38",
 "@rarible/web3-ethereum": "0.12.47",
```

Thank you!

**Comment by dsuthardeqode** [comment]
@zakariamofaddel You may the issue.
