### ISSUE TITLE
Metadata & Image on sdk.mint()

### ISSUE THREAD

**Issue by 4myr** [rarible/sdk#132]
hi.

how can i set image for a mint request.
also i would like to know how is for metadata & attributes?

**Comment by 4myr** [comment]
solved!

according to rarible documentation, meta data of an item will fetch from IPFS url that set in the mint request

so i used Pinata sdk to uploading meta data json using pinJSONToIPFS method and i set uri property in mintResponse.submit request to IPFS url that Pinata given to me.
also i used _rarible.nft.preprocessMeta_ to verify meta data that i give to pinJSONToIPFS.

**Comment by RafayelKh** [comment]
Hey @4myr, hope you are doing well!
I have a question about **rarible.nft.preprocessMeta**. How did you use that function, which args did you pass? Thanks!
