### ISSUE TITLE
Wallet undefined on sdk.nft.mint(mintRequest).submit

### ISSUE THREAD

**Issue by unzyp** [rarible/sdk#137]
Hi,

I got Wallet undefined error while trying to submit mint request, the setup is done like this

`const mintResponse = createRaribleSdk(new EthereumWallet(new Web3Ethereum({ web3: new Web3(provider), from: address })), "prod").nft.mint(mintRequest);`

`await mintResponse.submit({"ipfs://ipfs/QmYNJJLZJGenvjKu4yQPVDq3F7HaUt113r8Ah7dAK18uLV", 1, lazyMint: true,[],[],});`

The address fetched from metamask, and appears on console.log. But it shows Wallet undefined while trying to submit the mint request.

`Wallet undefined at getRequiredWallet (get-required-wallet.js:6:1) at check-chain-id.js:16:1 ...`

Anyone can help?

**Comment by drummel** [comment]
UUUhhhg same!!! 
Here is a gist of my code:
https://gist.github.com/drummel/06e936808029645a060d93bb37f235fe

**Comment by drummel** [comment]
What is very weird to me in this is gist code above, is after calling `web3.eth.accounts.wallet.add(...)` ... the call to `await web3.eth.getAccounts()` returns `[]` even though `web3.eth.accounts.wallet` has the new account ¯\_🐻_/¯.

**Comment by mvanhalen** [comment]
I´m also having this now and a client as well. Is this related to some metamask update or something else? Used to work fine. Tried install / reinstall metamask but keep getting this error. Other functions like getting collections for wallet work fine

**Comment by ex1st0r** [comment]
@mvanhalen Could you share your code?

**Comment by mvanhalen** [comment]
> 

Yeah metamask manually connected before that and linked. This stuff all works and SDK is initialized correctly. After that collections can be queried through SDK calls

**Comment by mvanhalen** [comment]
> @mvanhalen Could you share your code?

We insert the window.ethereum object like this:

` const ethersWeb3Provider = new ethers.providers.Web3Provider(window.ethereum)
  const ethersProvider = new EthersWeb3ProviderEthereum(ethersWeb3Provider)
  const ethWallet = new EthereumWallet(ethersProvider)
  raribleSdk = new createRaribleSdk(ethWallet, 'prod')
`

**Comment by buisine** [comment]
experiencing same issue using web3, ethers, sdk connector methods.
new sdk(wallet,network) goes fine, then createcollection or .submit on mint is always throwinf Wallet undefined

**Comment by evgenynacu** [comment]
Sorry for reallt long reply.
@buisine @mvanhalen and others, do you experience any issue regarding the topic?

Feel free to reopen the issue if you do
