### ISSUE TITLE
Metadata URI Metamask issue

### ISSUE THREAD

**Issue by dsuthardeqode** [rarible/sdk#154]
I am trying to lazy-mint and sell at the same time using multichain sdk. I am providing the whole URI link but metamask is picking only the id of it from params, and end of the point the rinky test app shows a corrupted NFT item on my item.

**Comment by 4myr** [comment]
Check your item in rinkeby.rarible.com
If meta data of that item is corrupted in rarible too, use Refresh metadata button, then you can see that problem will be fixed.

if by using this solution your problem has fixed, i can say that this problem will fix when you migrate to mainnet network.

**Comment by dsuthardeqode** [comment]
Hey @4myr , thank you for the response. I have tried multiple times by reloading meta data on rinkby.rarible, but the issue is the same. It does not load the data.

**Comment by 4myr** [comment]
> Hey @4myr , thank you for the response. I have tried multiple times by reloading meta data on rinkby.rarible, but the issue is the same. It does not load the data.

hey, i think your meta data json is not clean and its corrupted.
use `preprocessMeta` method before mint to transform your json to standard form like this:

```
raribleSDK.nft.preprocessMeta({
 # ...
 image: {
   url: ...,
   mimeType: ...
 },
 animation: {
   url: yourVideoOrMp3Url,
   mimeType: 'video/mp4',
 },
 external: null,
});
```

then upload result of this method to ipfs (like pinata.cloud with pinToJSON method)
your tokenURI will be : ipfs://ipfs/${hash}
