### ISSUE TITLE
GetActivitiesByItem always empty

### ISSUE THREAD

**Issue by alexisdavidson** [rarible/sdk#160]
Hi, I am trying to get the latest activities of an item using the following:

https://api.rarible.org/v0.1/activities/byItem?type=SELL&itemId=TEZOS:BLJR9hQ9Lbkq43yXrDgToK4vupMuyE2H5BoqKzEbnXPHPtGqFY2_16:2

I've tried many different types, item ids, starting with the contractId and followed by the token id. The activities list I receive is always empty. Any ideas?

**Comment by 4myr** [comment]
where is your token has minted?

**Comment by alexisdavidson** [comment]
> where is your token has minted?

Sorry I don't understand the question

**Comment by iskurenkov** [comment]
@alexisdavidson [Here](https://multichain.redoc.ly/v0.1/tag/activity-controller#operation/getActivitiesByItem) is more information on how to use this method. For example: https://api.rarible.org/v0.1/activities/byItem?type=MINT,LIST&itemId=TEZOS:KT1Lam6e8o62gsKtcaGkpVrpCUhA1Rs5nb3H:18&size=10

It's just that you specify in the request not the address of the item, but the address of the block.
