### ISSUE TITLE
MP3 and MP4 support

### ISSUE THREAD

**Issue by staminna** [rarible/sdk#174]
Is it possible to mint MP3 and MP4 files?
if so, how?

Thanks

**Comment by 4myr** [comment]
Yes, just set animation_url in metadata to your file link, then upload metadata to IFPS (ex. PinataCloud) and boom...

**Comment by staminna** [comment]
Dear 4mry

I am using the [https://moralis.io/how-to-mint-nfts-for-free-without-paying-gas-fees/ ](https://moralis.io/how-to-mint-nfts-for-free-without-paying-gas-fees/ )and I think it isn't using the SDK.

Thanks again

**Comment by 4myr** [comment]
> Dear 4mry
> 
> I am using the [https://moralis.io/how-to-mint-nfts-for-free-without-paying-gas-fees/ ](https://moralis.io/how-to-mint-nfts-for-free-without-paying-gas-fees/)and I think it isn't using the SDK.
> 
> Thanks again
there is no different.
i think metadata structure must be common in nft token

i should say that all of nft data included name, description, image, video, audio should save on IPFS and we call it metadata, it should be in JSON format:

so try this structure and upload it IPFS:
```json
{
"name": ITEM_NAME,
"description": ITEM_DESCRIPTION,
"image": IMAGE_URL_UPLOADED_ON_A_STORAGE,
"animation_url": VIDEO/AUDIO_URL_UPLOADED_ON_STORAGE,
"external_url": null,
"attributes": []
} 
```
