### ISSUE TITLE
Check action required set approval

### ISSUE THREAD

**Issue by 4myr** [rarible/sdk#190]
hey.

when i use `rarible.sell` method, if that item minted on rarible contract it don't need any transaction to sell on fixed price.
but when i used this method on items they minted on another platforms and contract it needs a transaction for set approval.

how can i check that , is this item needs set approval before call `rarible.sell` method using sdk and APIs?

**Comment by ex1st0r** [comment]
Hi!
When you call sell method our approve method checks already existed approvals for NFT and if it doesn't exist it will be approved by new approve transaction.
Our SDK don't provide external method for checking approvals

**Comment by 4myr** [comment]
> Hi! When you call sell method our approve method checks already existed approvals for NFT and if it doesn't exist it will be approved by new approve transaction. Our SDK don't provide external method for checking approvals

is there any solution for this problem (even without sdk) ?
