### ISSUE TITLE
staging: sdk.nft.createCollection succeeds but collection not available on rinkeby.rarible.com

### ISSUE THREAD

**Issue by vicwtang** [rarible/sdk#205]
This used to work but no longer.
create collection with:
params= {
        "blockchain": "POLYGON",
        "asset": {
            "assetType": "ERC721",
            "arguments": {
                "name": "testpoly1",
                "symbol": "testpoly1",
                "baseURI": "https://ipfs.rarible.com",
                "contractURI": "https://ipfs.rarible.com",
                "isUserToken": true,
                "operators": []
            }
        }
    }
sdk.nft.createCollection(params)
result: {
    "tx": {
        "transaction": {
            "receipt": {},
            "hash": "0xe62633eea5a9add246f5a43b2d40ce34bfc2a680a9362b552687d7d85009fddb",
            "data": "0x27050d1f00000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000018000000000000000000000000000000000000000000000000000000000000001c02a16e53a84bbf0100af4b75e8a06f44985b5cda5dc99e6a70e6ee3b8b5cd048b000000000000000000000000000000000000000000000000000000000000000974657374706f6c79310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000974657374706f6c79310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001868747470733a2f2f697066732e72617269626c652e636f6d0000000000000000000000000000000000000000000000000000000000000000000000000000001868747470733a2f2f697066732e72617269626c652e636f6d00000000000000000000000000000000000000000000000000000000000000000000000000000000",
            "nonce": 561,
            "from": "0x497f9faea098e12613ace222dcdca0cf91332c63",
            "to": "0xa85180a21786ba65b0778be1cb5cba5e5c6cd21d"
        },
        "network": "mumbai",
        "blockchain": "POLYGON"
    },
    "address": "POLYGON:0xFDCBC4c241140B39A9e0D0410b0Da05c9BC52fd2"
}

subsequently call:
https://api-staging.rarible.org/v0.1/collections/POLYGON%3A0xFDCBC4c241140B39A9e0D0410b0Da05c9BC52fd2
result: {"code":"NOT_FOUND","message":"Collection with id 0xfdcbc4c241140b39a9e0d0410b0da05c9bc52fd2 not found"}
Note the above call is also made by sdk.nft.mint(), which also fails.

collection also does not appear in collection list of owner.

ALSO. atttempting to create the collection manually on rinkeby.rarible.com spins after wallet signing with screen: 
Follow steps
Deploy contract
Deploy code for the new collection smart contract
Please advise.

Thanks!
Victor

**Comment by vicwtang** [comment]
This is also occurs for Tezos:
create collection succeeds:
{
    "tx": {
        "transaction": {
            "hash": "op4uKYT6CS828mKwqsR18kaEMUKZJEtU5dYWYsnkQA9gGePZybH",
            "contract": "KT1KXPEjohRgZ6G5Kz2zkgqapVRpmnRVtAXX"
        },
        "network": "hangzhou",
        "blockchain": "TEZOS"
    },
    "address": "TEZOS:KT1KXPEjohRgZ6G5Kz2zkgqapVRpmnRVtAXX"
}

https://test-tezos-api.rarible.org/v0.1/collections/KT1KXPEjohRgZ6G5Kz2zkgqapVRpmnRVtAXX - reports not found.

packages installed:
        "@rarible/connector": "^0.8.52-beta17",
        "@rarible/ethers-ethereum": "^0.12.64",
        "@rarible/sdk": "^0.8.52-beta17",
        "@rarible/sdk-wallet": "^0.8.52-beta17",
        "@rarible/sdk-wallet-connector": "^0.8.6-alpha.4",
        "@rarible/types": "^0.9.3",
        "@rarible/web3-ethereum": "^0.12.64",

**Comment by sathishquy** [comment]
i am also get same issue ( after creation collection not found ) 

but not all times 

occasionaly occurs

**Comment by ex1st0r** [comment]
Indexing of new collections can take some time
