### ISSUE TITLE
MintAndSell not putting new mints on marketplace with a price

### ISSUE THREAD

**Issue by vicwtang** [rarible/sdk#225]
I am calling the sdk.nft.mint with the following:
		let mintDetails = {
			uri: `ipfs://ipfs/${meta.metaCid}`,
			creators: [{
				account: creator,
				value: 10000,
			}],
			royalties: [{
				account: royaltyAccount,
				value: parseInt(process.env.NEXT_PUBLIC_ROYALTY_PERCENT)
			}],
			lazyMint: lazy,
			supply: 1,
		}
		if (meta.price) {
			mintDetails.price = meta.price
			mintDetails.currency = meta.currency
		}
		const result = await action.submit(mintDetails)

This was called for both ETHEREUM (lazy=true) and TEZOS, with currency set to "ETH" or "XTZ" respectively.
In both cases, the call succeeded and a tokenId was returned. HOWEVER, not one time did the NFT take the price and get listed for sale.

This required a subsequent sdk.order.sell call in order to successfully set the NFT for sale.

**Comment by ex1st0r** [comment]
Action submit of sdk.nft.mintAndSell returns orderId if result was successfully. You can check order by 
`ts
const order = await sdk.apis.order.getOrderById({ id: result.orderId })
`
If you didn't see order on the market, but it exists after calling sdk.apis.order.getOrderById method, you should await until order will be visible

**Comment by vicwtang** [comment]
Hi Alexsandr,
I neglected to store the OrderId in my mintAndSell call. I will going
forward.
I do not know if I received an orderid for the 3000eth lazy mints or the
1000tezos mints done with the MintAndSell method.
I dont know why none of these would have failed to create an orderId.

This call returns no orders for item
https://api.rarible.org/v0.1/orders/sell/byItem?itemId=TEZOS:KT1X8EiYF9tomiDVGagMV8ubrEhpqRfXEq1b:984

{"orders":[]}

Looking at the item details, it also shows no sell order info.
https://api.rarible.org/v0.1/items/TEZOS:KT1X8EiYF9tomiDVGagMV8ubrEhpqRfXEq1b:984

{"id":"TEZOS:KT1X8EiYF9tomiDVGagMV8ubrEhpqRfXEq1b:984","blockchain":"TEZOS","collection":"TEZOS:KT1X8EiYF9tomiDVGagMV8ubrEhpqRfXEq1b","contract":"TEZOS:KT1X8EiYF9tomiDVGagMV8ubrEhpqRfXEq1b","tokenId":"984","creators":[{"account":"TEZOS:tz1faBsSSSNj1iKnwzr6SMFA6g8EmZdU5kCn","value":10000}],"owners":[],"royalties":[{"account":"TEZOS:tz1V2QeJfHCg2MTSRm3h7Rj46sBNMcPsGkwi","value":200}],"lazySupply":"0","pending":[],"mintedAt":"2022-05-16T00:54:29Z","lastUpdatedAt":"2022-05-16T00:54:29Z","supply":"1","meta":{"name":"Unnamed
item","attributes":[],"content":[],"restrictions":[]},"deleted":false,"auctions":[],"totalStock":"0","sellers":0}

Why did MintAndSell not work???

NOTE. I am able to successfully call sdk.order.sell after the fact for Eth
and Tezos. Tezos was timing out last week, but working today so I am
currently iterating thru all 1000 minted tezos nfts to set sell order.

Thanks
Vic

**Comment by ex1st0r** [comment]
Hi!
Try mintAndSell with @rarible/sdk 0.9.4 version, it should work
