### ISSUE TITLE
packages/example deploy page fails with Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by bobwith2bees** [rarible/sdk#246]
1. Follow setup instructions in rarible/sdk/packages/example/README.md
2. Have wallet with Mumbai MATIC tokens for gas
3. Server starts
4. Navigate to Connect page
5. Disconnect Wallet (if connected)
6. Environment -> Staging
7. Metamask <connects to wallet>
8. Navigate to Deploy Token Page
9. Fill out token details (with Private Collection selected)
10. Deploy
11. Fails with "Request rejected - Cannot read properties of undefined (reading 'map')"

12. Unselect Private Collection you get a different error: 'Request rejected - Config chainId=4, but wallet chainId=8000

![2022-05-31_14-13-00](https://user-images.githubusercontent.com/81196211/171285485-da556910-4291-47e7-a8b9-2fc89b303bfb.jpg)
 --
1)  My immediate need is to deploy a contract with isPrivate so that I can use the MinterAccess Controls
2) Is a way to verify the setting of isPrivate (without having to mint and see if it fails)? 
Polygon explorer workarounds are fine - I just could not get the tokenFactory function calls visible to deploy from my browser.  https://mumbai.polygonscan.com/address/0xa85180a21786bA65b0778bE1cb5CBA5E5c6cD21d#code

**Comment by ex1st0r** [comment]
fixed
