### ISSUE TITLE
Documentation: Add support for new blockchain 

### ISSUE THREAD

**Issue by minahil-imtiaz** [rarible/sdk#252]
Hi, 

I have explored [examples](https://docs.rarible.org/reference/reference-overview/) and [contribution documentation](https://github.com/rarible/protocol/blob/main/CONTRIBUTING.md) but unfortunately couldn't find resources citing procedure to support a new blockchain in the SDK. 

Can you please help us with it by mentioning the relevant documents, if you have any?

Thanks.

**Comment by ex1st0r** [comment]
Hi!
We haven't public documentation procedure for adding new blockchain. You can ask more in our discord
