### ISSUE TITLE
Buy function backend not compatible with opensea sdk

### ISSUE THREAD

**Issue by phulelouch** [rarible/sdk#275]
![Screenshot from 2022-06-25 12-55-24](https://user-images.githubusercontent.com/62769629/175755715-50218b60-f7ed-468f-affb-ac1344ddabf6.png)

This happen when I trying backend buy function: https://github.com/rarible/sdk/blob/master/packages/sdk-examples/src/backend/ethereum/buy.ts. Where account was not define:
![2022-06-25-13:00:53_1920x1080_scrot](https://user-images.githubusercontent.com/62769629/175755754-a87a07e1-0b44-4e56-aea3-6743d0c232c9.png)

**Comment by ex1st0r** [comment]
That was fixed since v0.9.11-beta.9 version
