### ISSUE TITLE
getOrderById says order with id not found

### ISSUE THREAD

**Issue by dsuthardeqode** [rarible/sdk#326]
## `getOrderById` says order with id not found

https://testnet-api.rarible.org/v0.1/orders/ETHEREUM%3A0x9e8066fa55406cc9417615bf945f3d9d5f4a8358e670a058954b7fce43008580

At the same time, I am able to fetch other items data using the same api.

**Comment by mystdeim** [comment]
It seems we don't have this order in the DB.

**Comment by evgenynacu** [comment]
@dsuthardeqode why do you think it should be there?
Feel free to reopen if you consider this as an issue on our side
