### ISSUE TITLE
sdk.auction does not exist on type 'IRaribleSdk'

### ISSUE THREAD

**Issue by QalbeHabib** [rarible/sdk#364]
I'm currently  using  "@rarible/sdk": "0.9.37", a version of rarible SDK 
Here I am facing a problem in finding sdk.auction() 
It said any
" Property 'auction' does not exist on type 'IRaribleSdk' "
I checked IRaribleSdk as well and didn't find out there.

please let me know I anyone finds it solution.

**Comment by mostafa-rio** [comment]
@QalbeHabib Did you tried updating to the latest version? the current version is [0.13.21](https://github.com/rarible/sdk/releases)
