### ISSUE TITLE
Goerli testnet supports

### ISSUE THREAD

**Issue by youngqqcn** [rarible/sdk#395]
I successfully deployed a collection by using `package/example` at `Goerli`, but I couldn't `mint` with the deployed `Collection ID`(contract address) , the error msg as below:

```
{ "status": 400, "url": "https://testnet-api.rarible.org/v0.1/collections/0x66a1037a48b6a2469cf740ad9ac42bd47edf9573", "data": { "code": "BAD_REQUEST", "message": "Illegal format for ID: '0x66a1037a48b6a2469cf740ad9ac42bd47edf9573', blockchain prefix not found" } }
```

**Comment by ex1st0r** [comment]
You should use blockchain preffix in collection address, like https://testnet-api.rarible.org/v0.1/collections/ETHEREUM:0x66a1037a48b6a2469cf740ad9ac42bd47edf9573
But as far as I see it's non-collection address https://goerli.etherscan.io/address/0xfa44ce1cb30a793d3357536f5b95c5bf8b8565e3
