### ISSUE TITLE
how to check item is buyable directly?

### ISSUE THREAD

**Issue by aliray** [rarible/sdk#403]
use api quey the sellorder , & how to check which order i should take 
reponse have many orders, which on i should to take & buy?

below is https request
https://api.rarible.org/v0.1/orders/sell/byItem?itemId=ETHEREUM:0x231d3559aa848bf10366fb9868590f01d34bf240:5612

response:
{
    "orders": [
        {
            "id": "ETHEREUM:0x373d17db5e998cd9f79f05dcb5cc04dc647a626393b7b80b34dbfada451764f9",
            "fill": "0",
            "platform": "OPEN_SEA",
            "status": "ACTIVE",
            "startedAt": "2022-12-09T06:52:44Z",
            "endedAt": "2023-01-08T06:52:44Z",
            "makeStock": "1",
            "cancelled": false,
            "optionalRoyalties": false,
            "createdAt": "2022-12-09T06:52:51.115Z",
            "lastUpdatedAt": "2022-12-09T06:52:51.115Z",
            "dbUpdatedAt": "2022-12-09T06:53:08.643Z",
            "makePrice": "0.541",
            "makePriceUsd": "693.0333212615038894",
            "maker": "ETHEREUM:0x0e5af446621c2b2b45602c34870d6b10dfb81a43",
            "make": {
                "type": {
                    "@type": "ERC721",
                    "contract": "ETHEREUM:0x231d3559aa848bf10366fb9868590f01d34bf240",
                    "tokenId": "5612"
                },
                "value": "1"
            },
            "take": {
                "type": {
                    "@type": "ETH",
                    "blockchain": "ETHEREUM"
                },
                "value": "0.541"
            },
            "salt": "0x360c6ebe0000000000000000000000000000000000000000f0b411a9234e23c3",
            "signature": "0x5bec7e6c043fc336ef644916a3ee703baae749ab8ae7f4fa3a433327e957fbd49f83723b23a665db2bfbb17c1359b5d5064a867f1378ef0369aa52032a84de03",
            "data": {
                "@type": "ETH_BASIC_SEAPORT_DATA_V1",
                "protocol": "ETHEREUM:0x00000000006c3852cbef3e08e8df289169ede581",
                "orderType": "FULL_RESTRICTED",
                "offer": [
                    {
                        "itemType": "ERC721",
                        "token": "ETHEREUM:0x231d3559aa848bf10366fb9868590f01d34bf240",
                        "identifierOrCriteria": "5612",
                        "startAmount": "1",
                        "endAmount": "1"
                    }
                ],
                "consideration": [
                    {
                        "itemType": "NATIVE",
                        "token": "ETHEREUM:0x0000000000000000000000000000000000000000",
                        "identifierOrCriteria": "0",
                        "startAmount": "500425000000000000",
                        "endAmount": "500425000000000000",
                        "recipient": "ETHEREUM:0x0e5af446621c2b2b45602c34870d6b10dfb81a43"
                    },
                    {
                        "itemType": "NATIVE",
                        "token": "ETHEREUM:0x0000000000000000000000000000000000000000",
                        "identifierOrCriteria": "0",
                        "startAmount": "13525000000000000",
                        "endAmount": "13525000000000000",
                        "recipient": "ETHEREUM:0x0000a26b00c1f0df003000390027140000faa719"
                    },
                    {
                        "itemType": "NATIVE",
                        "token": "ETHEREUM:0x0000000000000000000000000000000000000000",
                        "identifierOrCriteria": "0",
                        "startAmount": "27050000000000000",
                        "endAmount": "27050000000000000",
                        "recipient": "ETHEREUM:0xff59b4b3d52728f78020414c720164a17c08f499"
                    }
                ],
                "zone": "ETHEREUM:0x004c00500000ad104d7dbd00e3ae0a5c00560c00",
                "zoneHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "conduitKey": "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000",
                "counter": 18
            }

        },
        *** many other orders

    ]
}

**Comment by ex1st0r** [comment]
you can use "bestSellOrder" field (if exists) in response of https://api.rarible.org/v0.1/items/ETHEREUM:0x231d3559aa848bf10366fb9868590f01d34bf240:5612
