### ISSUE TITLE
Wrong deep linking in iOS?

### ISSUE THREAD

**Issue by ValenCassa** [rarible/sdk#407]
I'm trying to use the mint method in iOS - while connected w/ WalletConnect - with no success, it doesn't detect that you have metamask already installed and does not give you any options, just the app store. I tried the same thing in Android and it worked, that's why I suppose it's a deep linking issue. 

I also found [this issue](https://github.com/MetaMask/metamask-mobile/issues/3965) which is already fixed. 

Just in case it helps, the Wallet Connect connector detects that metamask is already installed.

**Comment by ex1st0r** [comment]
No
You can try to fix it with provider's middleware. For example: at first you start target SDK method, then catch transaction in middleware and let user to confirm operation by click on some button. It means wallet interaction occurs as soon as possible  (second of important rules, [read more](https://docs.walletconnect.com/2.0/ios/guides/mobile-linking#ios-app-link-constraints))

**Comment by evgenynacu** [comment]
AFAIK this is not reproducible any more

Let me know if you need help here
Closing the issue. Feel free to reopen if needed
