### ISSUE TITLE
Auction - ETHEREUM:undefined

### ISSUE THREAD

**Issue by NitishBeejawat** [rarible/sdk#411]
const ethCurrency: EthErc20AssetType = {
        "@type": "ERC20",
        contract: toContractAddress(
          "ETHEREUM:0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"
        ),
      };

      const price: number = Number(bid);
      const amount: number = 1;

      const orderRequest: PrepareOrderRequest = {
        itemId: toItemId(tokenUnionAddress),
      };

      const bidResponse = await sdk?.order.bid(orderRequest);

      const response = await bidResponse?.submit({
        amount,
        price,
        currency: ethCurrency,
      });

Can anyone let me know what contract address I can use for goerli testnet and mumbai testnet since I am getting "ETHEREUM:undefined" issue.

Earlier I was working with RINKEBY TESTNET so I have used above addres but now I have switched to GOERLI testnet so what address can I use.

**Comment by vsthakur1quytech** [comment]
Getting same issue.
Please help

**Comment by webtech2412** [comment]
@evgenynacu can you pls help with this issue.

**Comment by ex1st0r** [comment]
WETH contract address the same for Goerli network

**Comment by NitishBeejawat** [comment]
Yes I have used that only

**Comment by NitishBeejawat** [comment]
@ex1st0r I have tried many things but on my end bidding is not working. Could you provide some sample code that I can use.

I am getting 2 kind of issues while placing a bid:
1. When I am placing a bid I am getting **POLYGON:undefined** response of bid action - version **^0.9.13-beta.imx.2**
2. When I am trying to upgrade the library the I am getting **Error: Unrecognized RequestCurrency undefined** rarible sdk - version **0.13.10**


Please check below screenshots for more reference

![image](https://user-images.githubusercontent.com/110381182/221427961-8999ac1b-4a6e-489b-a2f2-2d71ad6f2c8a.png)
![image](https://user-images.githubusercontent.com/110381182/221428043-e2a6689f-7ec4-437f-a0f5-22a6097cd2dc.png)
