### ISSUE TITLE
How to connect to Binance Smart Wallet @rarible/connector

### ISSUE THREAD

**Issue by phananhvusafemoon** [rarible/sdk#423]
Hi everyone.
I don't find guide connect with binance smart wallet use @rarible/connector.

**Comment by mostafa-rio** [comment]
Web3Modal package is a better way to connect. they frequently update and maintain their connectors.
just connect and pass the provider to createRaribleSdk method

**Comment by evgenynacu** [comment]
@phananhvusafemoon rarible connectors are not required for you if you use SDK
It's optional

Use rarible connectors if you want to connect wallets from different blockchains
