### ISSUE TITLE
TypeError: Cannot assign to read only property `totalFilled` of object `[object Array]`

### ISSUE THREAD

**Issue by sk1122** [rarible/sdk#458]
[orderStatus](https://github.com/rarible/sdk/blob/master/packages/ethereum/sdk/src/order/fill-order/seaport-utils/seaport-utils.ts#L96) is readonly for some reason and because of that can't buy nft on polygon

**Comment by ex1st0r** [comment]
Could you show code to reproduce it (maybe on codesandbox)?

**Comment by sk1122** [comment]
https://gist.github.com/sk1122/42405d40ecd072b3e80cc7cb723a3da9

you can try this gist, `order.buy` function is failing

**Comment by sk1122** [comment]
best solution is to change [this](https://github.com/rarible/sdk/blob/master/packages/ethereum/sdk/src/order/fill-order/seaport-utils/seaport-utils.ts#L73) from `const` to `let`

**Comment by mostafa-rio** [comment]
@sk1122 my question is how do you get a "orderId" to pass to createNftBuyOrder function in the first place?
as in the [SDK page](https://github.com/rarible/sdk#buy) mentioned you can use order.buy after you call findOrderById(orderId) on line 3 and let the user directly complete the transaction.

**Comment by sk1122** [comment]
That is internal orderId and that function is also internal

**Comment by mostafa-rio** [comment]
@ex1st0r could you mention the framework you're using and past the exact code you coded for the "buy nft on polygon"

**Comment by NBMSacha** [comment]
+1, Did someone try how to solve this problem ?

**Comment by evgenynacu** [comment]
Does anyone experience this?
We don't see these exceptions anymore in our logs

Closing the issue. Feel free to reopen if you experience this issue
