### ISSUE TITLE
Error: The fulfiller does not have the balances needed to fulfill.

### ISSUE THREAD

**Issue by mostafa-rio** [rarible/sdk#459]
I'm trying to make a simple buy transaction in frontend:

hers is the code block:

` const res = await rarible.apis.order.getSellOrdersByItem({
      itemId: 'ETHEREUM:0x79fcdef22feed20eddacbb2587640e45491b757f:964',
      status: (['ACTIVE'] as [OrderStatus.OrderStatus.ACTIVE])
    }) 
       
    const tx = await rarible.order.buy({
      orderId: res.orders[0].id,
      amount: 1,
    })     
await tx.wait()`

**Comment by ex1st0r** [comment]
It means is not enough funds on your wallet (on mainnet)

**Comment by mostafa-rio** [comment]
@ex1st0r thanks for the answer.
