### ISSUE TITLE
Integration with rarible/sdk returns `SyntaxError: Unexpected token '||='` in production.

### ISSUE THREAD

**Issue by theiceeman** [rarible/sdk#481]
<img width="676" alt="Screen Shot 2023-05-21 at 4 58 58 PM" src="https://github.com/rarible/sdk/assets/53199415/bb8e1ba7-71b0-4d1a-816f-7446a5b26306">

My integration with rarible/sdk keeps throwing this error in production.
This does not happen locally, but the stack trace shows its coming from one of the @rarible dependencies.

What could be causing this please?
My node version is v16.

Thanks.

**Comment by ex1st0r** [comment]
Hi
Operator "||=" is allowed https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment
Check error on your side
