### ISSUE TITLE
429 Error on server side ( using API Key) 

### ISSUE THREAD

**Issue by mostafa-rio** [rarible/sdk#513]
We are using Rarible APIs in our node.js code and even though we're using API Key in our request we're still getting 429 errors.
Is there any pro version available?

```
async getItemById(itemWithPrefix: string): Promise<RaribleItem> {
    const result = await this.httpService.axiosRef.get(
      ${this.url}/items/${itemWithPrefix},
      { headers: { 'X-API-KEY': this.apikey } },
    );
    return result.data;
  }
```

**Comment by ex1st0r** [comment]
Could you check it again? Should be working after today's update

**Comment by mostafa-rio** [comment]
@ex1st0r Yes, I can confirm it's working fine. Thanks for the update.
