### ISSUE TITLE
engine Not compatible with your version of node/npm: @imtbl/imx-sdk@1.43.7

### ISSUE THREAD

**Issue by mvanhalen** [rarible/sdk#523]
We run node 18 with a Vercel instance. node 16 will be deprecated soon. Yet the sdk references @imtbl/imx-sdk@1.43.7 which needs node 16 and lower. It´s outdated. Version 2 and up support node 18. Tried with Rarible sdk version 0.13.49

Please create an SDK version without Immutable or update the reference.

**Comment by evgenynacu** [comment]
@mvanhalen sorry for the late reply

I suppose this should be fixed already. We migrated to newer version of imx-sdk
Feel free to reopen if you are experiencing issues still
