### ISSUE TITLE
is it possible to query items by collection and by owner?

### ISSUE THREAD

**Issue by zakariamofaddel** [rarible/sdk#65]
I see there is no api for this in the SDK, what is the suggested way to get items by collection and make sure that they are owned by a specific account?

I see that Rarible does something like this, is it possible somehow using this SDK or some other API?
![Screenshot 2021-12-15 211321](https://user-images.githubusercontent.com/66852346/146250360-1748e8cf-3c17-419c-8ad1-05ca76eb6c4c.png)

**Comment by ex1st0r** [comment]
@zakariamofaddel Sure, to find items by collection or owner you can use `
const sdk = createRaribleSdk(...)
await sdk.apis.item.getItemsByCollection({ collection: "ETHEREUM:0x..." })
//or
await sdk.apis.item.getItemsByOwner({ owner: "ETHEREUM:0x..." })
`
if you want to make sure that some item owned by account `
await sdk.apis.ownership.getOwnershipById({
  ownershipId: `${blockchain}:${tokenContractAddress}:${tokenId}:${owner}`, // ex. "ETHEREUM:0x60f80121936a0d46b5279700f9df786054aa5ee5:12345:0x60f80121c31a0d46b5279700f9df786054aa5ee5"
})
`
If ownership was not been found you get a 404 error, more in our docs https://api.rarible.org/v0.1/doc#operation/getOwnershipById
